USE pyu;

CREATE TABLE IF NOT EXISTS users (
    id            INT AUTO_INCREMENT PRIMARY KEY,
    google_id     VARCHAR(255) DEFAULT NULL UNIQUE,
    email         VARCHAR(255) NOT NULL UNIQUE,
    username      VARCHAR(255) DEFAULT NULL,
    name          VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) DEFAULT NULL,
    avatar_url    VARCHAR(500) DEFAULT NULL,
    last_login_at TIMESTAMP NULL DEFAULT NULL,
    created_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);